ARG runtime_img

FROM $runtime_img
ENV CGO_ENABLED=0

WORKDIR /go/src/github.com/chadgrant/servicestatus

COPY go.mod go.sum ./
RUN go mod download

COPY Makefile *.go ./
COPY api ./api
COPY gen ./gen
COPY cmd ./cmd

CMD ["go","test","-v","./..."]