ARG runtime_img="golang:1.13"

FROM $runtime_img

WORKDIR /go/src/github.com/chadgrant/service-status

COPY go.mod go.sum ./
RUN go mod download

COPY Makefile main.go ./
COPY api ./api/

CMD ["go","test","-v","./..."]