ARG runtime_img="golang:1.13"

FROM $runtime_img

WORKDIR /go/src/github.com/chadgrant/servicestatus

COPY go.mod go.sum ./
RUN go mod download

COPY Makefile *.go ./
COPY api ./api
COPY gen ./gen
COPY cmd ./cmd

CMD ["go","test","-v","./..."]